### ISSUE TITLE
Future ideas for `balance_taxonomy`

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-gneiss#21]
**Improvement Description**
Showing the full taxonomy string from the root to the current level is usually how we display the taxonomic information. That would make the `Balance Taxonomy` barplot match q2-taxa a bit better.

Additionally, the proportion plot should probably have the full taxonomy string, since it is representing a given balance tip. Alternatively, it might make sense for those to be collapsed to the taxa level as well.

It would be nice if the scatter plot was also colored by the partition group when working with numeric metadata.

**Comment by ebolyen** [comment]
It also seems like the Proportion plot could concievably support more than two groups if the bars were vertical and colored with a group legend. You could still split the chart into numerator/denominator like it currently is, the split would just be vertical.

**Comment by ChrisKeefe** [comment]
`balance_taxonomy` was removed in 2020.2. Ok to close?
