### ISSUE TITLE
error if feature table samples aren't found in metadata

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-gneiss#25]
An error should be raised if any sample IDs in the feature table aren't present in the sample metadata. This is to match the behavior in QIIME 1 and 2 where metadata IDs can be a superset of the table IDs, but every table ID must have corresponding metadata.

[forum x-ref](https://forum.qiime2.org/t/warn-if-samples-features-are-filtered/2353?u=jairideout)

**Comment by Oddant1** [comment]
Is this still a relevant issue? The error definitely isn't being raised, but it looks like all of the methods that even use metadata in gneiss are deprecated.

**Comment by thermokarst** [comment]
It might still be relevant:

- https://docs.qiime2.org/2019.7/plugins/available/gneiss/gradient-clustering/

**Comment by mortonjt** [comment]
Thanks @thermokarst - yes this is still an outstanding issue

It'll boil down to something as follows here: https://github.com/qiime2/q2-gneiss/blob/master/q2_gneiss/cluster/_cluster.py#L93

```python
difference = set(table.index) - set(gradient.index)
if difference and not ignore_missing_samples:
            raise KeyError("There are samples not included in the mapping "
                           "file. Override this error by using the "
                           "`ignore_missing_samples` argument. Offending "
                           "samples: %s"
                           % ', '.join(sorted([str(i) for i in difference])))
```

Concerning deprecation - the stats methods are being deprecated in favor of other differential abundance methods such as [songbird](https://github.com/biocore/songbird) and _hopefully_ [aldex2](https://github.com/mortonjt/q2-aldex2). CC @ggloor

**Comment by Oddant1** [comment]
And this should be a thing in all q2-gneiss methods taking a Metadata or MetadataColumn as input?

**Comment by mortonjt** [comment]
Yes - especially if it isn't deprecated

**Comment by Oddant1** [comment]
:laughing: those poor lonely deprecated methods

**Comment by Oddant1** [comment]
I'm not finding any relevant methods other than `gradient_clustering`

**Comment by Oddant1** [comment]
Also, do we want `ignore_missing_samples` arguments to be included in any relevant methods?

**Comment by mortonjt** [comment]
Why not - that's the parameter used in emperor. There's definitely the use
case that you do want to remove non overlapping samples.

**Comment by Oddant1** [comment]
is this exception already doing something similar to this?

![image](https://user-images.githubusercontent.com/10642616/62401675-0c8f6c00-b539-11e9-9062-80f11b187b31.png)

**Comment by mortonjt** [comment]
Not quite - that's testing to see if all of the samples are dropped. The
code previously tests to see if there is a complete overlap in samples

**Comment by Oddant1** [comment]
Yeah I realized that after looking at it a bit more closely

**Comment by ggloor** [comment]
yes we are getting close to having ALDEx2 up and running inside QIIME2. https://github.com/dgiguer is just putting the finishing touches on this
