### ISSUE TITLE
balance-taxonomy CSV header inconsistencies

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-gneiss#26]
**Bug Description**
When the artifact generated by qiime gneiss balance-taxonomy is exported with qiime tools export, the resulting files include a “numerator.csv” and “denominator.csv” file.

The “usual” header line in these files contains: Feature ID,0,1,2,3,4,5,6.

However, if the file only contains only one feature, then the header becomes: ,0,1,2,3,4,5,6. The Feature ID is missing. This isn’t a big deal unless one tries to aggregate multiple “numerator.csv” and “denominator.csv” files together, which then produces some problems.

**References**
[Ported wholesale from the forum](https://forum.qiime2.org/t/gneiss-balance-taxonomy-export-format-inconsistencies/2426?u=thermokarst)

**Comment by ChrisKeefe** [comment]
The `balance_taxonomy` visualizer was removed in v2020.2. Ok to close this?
