### ISSUE TITLE
statsmodels 0.9.0 appears to break existing tests

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-gneiss#39]
Should investigate updating tests, pinning `statsmodels`, or some other unconsidered option(s).

**Comment by thermokarst** [comment]
Failing tests on [`busywork`](https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/unit-test-q2-gneiss/builds/31).

**Comment by mortonjt** [comment]
It looks like an easy fix - just requires the labels to be renamed.

**Comment by thermokarst** [comment]
Thanks @mortonjt! Sounds like a plan to me. We should probably also update the conda recipe to pin the minimum version of `statsmodels`.
