### ISSUE TITLE
Split ilr-transform into two commands

### ISSUE THREAD

**Issue by mortonjt** [qiime2/q2-gneiss#41]
I think it may be a good idea to have two ilr transform commands, namely

- [ ] `ilr-hierarchical`
- [ ] `ilr-phylogenetic`

That way we can explicitly handle phylogenetic trees.  No need for the `assign-ids` command, especially if we can fold this inside of the `ilr-transform`.  Any thoughts?

**Comment by mortonjt** [comment]
@qiyunzhu is currently working on this for the latest q2 sprint

**Comment by ebolyen** [comment]
closed in #43
