### ISSUE TITLE
Add pseudocount parameter to visualizations

### ISSUE THREAD

**Issue by mortonjt** [qiime2/q2-gneiss#47]
Add pseudocount parameter to
 
Balance Taxonomy
https://github.com/qiime2/q2-gneiss/blob/master/q2_gneiss/plot/_plot.py#L31

Dendrogram heatmap
https://github.com/qiime2/q2-gneiss/blob/master/q2_gneiss/plot/_plot.py#L344

**Comment by ebolyen** [comment]
Fixed in #48
