### ISSUE TITLE
Error in gneiss tutorial

### ISSUE THREAD

**Issue by emankhalaf** [qiime2/q2-gneiss#51]
Hello,
I am following gneiss tutorial and I stuck at the beginning, when run 
qiime gneiss correlation-clustering \--i-table table.qza \--o-clustering hierarchy.qza

I got this error:
Plugin error from gneiss:

  Argument to parameter 'table' is not a subtype of FeatureTable[Composition].

Even when use my files, I got the same error.

Is there any updates for the plugin that not posted on the web

I wonder if any could help me.
Thanks

**Comment by mortonjt** [comment]
@emankhalaf could you post this to the qiime2 forums with the commands you used and the qiime2 version?

https://forum.qiime2.org/

**Comment by emankhalaf** [comment]
sure
